name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: lumen-sdk

      - name: Initialize
        working-directory: lumen-sdk
        run: |
          west init -l .
          west update -o=--depth=1 -n

      - name: Build firmware
        working-directory: lumen-sdk
        run: |
          west twister -T app -v --inline-logs --integration

      - name: Test
        run: ls > test.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: test.txt
