name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: lumen-sdk

      - name: Initialize
        working-directory: lumen-sdk
        run: |
          west init -l .
          west update -o=--depth=1 -n

      - name: Build firmware
        working-directory: lumen-sdk
        run: |
          west twister -T app -v --inline-logs --integration

      - name: Release
        working-directory: lumen-sdk
        uses: softprops/action-gh-release@v1
        with:
          files: |
            twister-out/lumen/app.debug/zephyr/app_update.bin
            twister-out/lumen/app.debug/zephyr/merged.hex
            twister-out/lumen/app.default/zephyr/app_update.bin
            twister-out/lumen/app.default/zephyr/merged.hex
